### ISSUE TITLE
[JS] ReferenceError: EclipseDittoJavascriptClientApi is not defined

### ISSUE THREAD

**Issue by flobaader** [eclipse/ditto-clients#28] opened 2019-11-06 12:17 UTC
Hi,

I want to use the client in a VueJs environment (with Webpack).
When I want to use the client I get the following error:

`ReferenceError: EclipseDittoJavascriptClientApi is not defined`

my code:

```
    static getDittoClient() {
        return DittoDomClient.newHttpClient()
            .withTls()
            .withDomain('example.com')
            .withAuthProvider(DomHttpBasicAuth.newInstance("username", 'password'))
            .apiVersion2()
            .build();
    }
```

reported source file:
```
var EclipseDittoJavascriptClient = (function (exports, dittoJavascriptClientApi_1_0Pre) {
'use strict';

[....]

}({}, EclipseDittoJavascriptClientApi));

//# sourceURL=webpack-internal:///./node_modules/@eclipse-ditto/ditto-javascript-client-dom_1.0-pre/dist/index.bundle.js
```

versions:
```
"@eclipse-ditto/ditto-javascript-client-api_1.0-pre": "^1.0.0-pre2",
"@eclipse-ditto/ditto-javascript-client-dom_1.0-pre": "^1.0.0-pre2",
```

**Comment by ffendt** [comment] 2019-11-06 14:58
Hi there,
thanks for your question. Can you provide a minimal example to reproduce the problem?

**Comment by flobaader** [comment] 2019-11-06 15:22
Hi,

thanks for the quick reply. I have set up a minimum Vue app with the Ditto import here: https://github.com/flobaader/ditto-js-client-undefined-example

Hopefully this helps.

**Comment by ffendt** [comment] 2019-11-07 08:28
Hi there,
thanks for the example. I was able to reproduce the problem with it.

I think the problem lies somewhere in webpack that does load the modules in a wrong way. As we can see from the error logs, `index.bundle.js` is used, which is the IIFE version of the client and thus should work in browser environments. The client also requires the api (`EclipseDittoJavascriptClientApi`) to be defined, which we should be able to solve by importing it. But until now I didn't find a way to tell webpack that it should declare the imported `EclipseDittoJavascriptClientApi` variable globally.

Maybe there is some special loader/resolver that needs to be used, but I didn't find any solution with my (obviously very poor) google skills. Did you already find any solution? If there is none, it would probably mean to rework the release build of the client to already include the api package.

**Comment by flobaader** [comment] 2019-11-07 09:54
Is there any reason why the api package is not included in the client packages? Because I guess that you would always need the api module with the same version as the client package. 
I will do some research to find out if there is any way to tell webpack where to find the API package.

**Comment by ffendt** [comment] 2019-11-07 10:06
The api package is not included to allow users to build their own implementation on top of it (just like the dom and node implementations that are provided currently). But yes, as we would expect to always use the same version, we could try to find a way to include the api directly into the clients instead of importing the api module.

**Comment by flobaader** [comment] 2019-11-07 14:29
Okay. My recommendation would be to allow users to implement the API with the existing package but to combine the API package with your implementations. Then everything should work fine (hopefully).

**Comment by vavido** [comment] 2020-12-17 14:09
I was able to prevent the original error by [shimming](https://webpack.js.org/guides/shimming/) the `EclipseDittoJavascriptClientApi` in the webpack config like so:
```javascript
plugins: [
      new webpack.ProvidePlugin({
        EclipseDittoJavascriptClientApi: '@eclipse-ditto/ditto-javascript-client-api_1.0',
      }),
],
```

However, I'm now getting the following error instead: 
```log
TypeError: class heritage dittoJavascriptClientApi.HttpBasicAuth is not an object or null
    EclipseDittoJavascriptClient index.bundle.js:209
    <anonymous> index.bundle.js:271
    <anonymous> index.bundle.js:274
    node_modules 27.js:10
    __webpack_require__ app.js:854
    fn app.js:151
    <anonymous> DittoClient.ts:8
    ts 27.js:46
    __webpack_require__ app.js:854
    fn app.js:151
    <anonymous> cjs.js:12
    node_modules cjs.js:22
    __webpack_require__ app.js:854
    fn app.js:151
    <anonymous> TestPage.vue:1
    ./src/pages/TestPage.vue?vue&type=script&lang=ts& 27.js:82
    __webpack_require__ app.js:854
    fn app.js:151
    <anonymous> TestPage.vue:1
    vue 27.js:70
    __webpack_require__ app.js:854
    fn app.js:151
    promise callback*TestPage router.ts:30
    resolveAsyncComponents vue-router.esm.js:2037
    flatMapComponents vue-router.esm.js:2064
    flatMapComponents vue-router.esm.js:2064
    flatMapComponents vue-router.esm.js:2063
    resolveAsyncComponents vue-router.esm.js:1999
    iterator vue-router.esm.js:2252
    step vue-router.esm.js:1898
    step vue-router.esm.js:1902
    runQueue vue-router.esm.js:1906
    confirmTransition vue-router.esm.js:2282
    transitionTo vue-router.esm.js:2152
    init vue-router.esm.js:2910
    beforeCreate vue-router.esm.js:1240
    VueJS 4
    createVue main.ts:147
    _callee$ main.ts:116
    Babel 10
    init dsb-vue-keycloak.umd.js:2522
    VueJS 3
    onReady dsb-vue-keycloak.umd.js:2528
    init dsb-vue-keycloak.umd.js:1013
vue-router.esm.js:2208
```

The offending line is the declartation of the `DomHttpBasicAuth` class inside the index.bundle.js of the dom client.

**Comment by ffendt** [comment] 2020-12-18 14:26
Hi @vavido,

I also tried again to get my hands dirty at this. It still seems to be the case, that the loader has issues with the IIFE module format used by the Ditto JS client. I was also able to reproduce your error (with a bit different error message, but at the same line) and at that point `dittoJavascriptClientApi_1_0` (i.e. `EclipseDittoJavascriptClientApi`) still was undefined, even though shimming it. Probably shimming also does not correctly work with IIFE modules.

The good news: I was able to fix this by telling webpack to not resolve dependencies via the `browser` property from `package.json` by just omitting it while resolving:
```
       resolve: {
            mainFields: ['module', 'main']
        }
```

The bad news: I think this might cause problems with modules that should be resolved via their `browser` property. Maybe one can use `['module', 'browser', 'main']` to at least try to load not-module-dependencies via their `browser` property. I'm also not deep enough into the different module/loader systems of javascript nowadays, so I really don't know if there's a clean solution or if we would need to reconfigure our IIFE build.

**Comment by vavido** [comment] 2020-12-21 10:03
Hi @ffendt, 
thank you for looking into this a bit more. 
I actually didn't think of telling webpack to not resolve the browser module.
I will try that in our "real-world" application and see if there is way to do this without breaking other dependencies. 

If that fails, I will have a look at the IIFE build settings, maybe something can be done there. 

In the case that there is no other solution, would you consider publishing "browser" and "webpack" builds seperately?

**Comment by ffendt** [comment] 2021-01-04 06:23
Hi @vavido,
yes, I would consider doing this, but this will also need some thoughts.

**Comment by vavido** [comment] 2021-01-04 15:15
In our case, your workaround seems to do the job, I added browser as the last entry of the resolve order. 
As far as I can tell right now, this only caused a problem with one of our dependencies which seems to be working better when resolved via its `browser` index.js. 

However, this can be fixed by importing the file directly, circumventing the webpack resolver.
In our case, the offending library was `consola`, with `  "browser": "dist/consola.browser.js"`, so `require('consola')` becomes `require('consola/dist/consola.browser.js')`. 

However, this might not work for every module, if the module itself `requires` or `imports` any other module, the import is resolved by webpack and the `module` version of the dependency will be bundled which is usually incompatible with the `browser` module.

Maybe the `browser` module of the client could be switched to an ES2015 module which should work better with webpack and is supported in all modern browsers: https://caniuse.com/es6

**Comment by ffendt** [comment] 2021-01-05 08:12
I think you're right. Actually we already provide it as an ES6 module with the `module` field. And thanks to you I also tried using the ES6 version in plain html and it worked 🎉. So probably we can just remove the iife bundling completely (and thus also the `browser` info).

**Comment by vavido** [comment] 2021-01-05 09:57
I just tested the configuration without IIFE in our webpack environment, works perfectly with just the default webpack configuration 👍

**Closed** 2021-04-15 11:24 UTC
Labels: javascript
